apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  selector:
    app.kubernetes.io/name: kbkb-manager
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
