//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kbkb) DeepCopyInto(out *Kbkb) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kbkb.
func (in *Kbkb) DeepCopy() *Kbkb {
	if in == nil {
		return nil
	}
	out := new(Kbkb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kbkb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbkbList) DeepCopyInto(out *KbkbList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kbkb, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbkbList.
func (in *KbkbList) DeepCopy() *KbkbList {
	if in == nil {
		return nil
	}
	out := new(KbkbList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KbkbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbkbSpec) DeepCopyInto(out *KbkbSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spawn != nil {
		in, out := &in.Spawn, &out.Spawn
		*out = new(SpawnSpec)
		**out = **in
	}
	if in.Versus != nil {
		in, out := &in.Versus, &out.Versus
		*out = new(VersusSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbkbSpec.
func (in *KbkbSpec) DeepCopy() *KbkbSpec {
	if in == nil {
		return nil
	}
	out := new(KbkbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbkbStatus) DeepCopyInto(out *KbkbStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbkbStatus.
func (in *KbkbStatus) DeepCopy() *KbkbStatus {
	if in == nil {
		return nil
	}
	out := new(KbkbStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpawnSpec) DeepCopyInto(out *SpawnSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpawnSpec.
func (in *SpawnSpec) DeepCopy() *SpawnSpec {
	if in == nil {
		return nil
	}
	out := new(SpawnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersusSpec) DeepCopyInto(out *VersusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersusSpec.
func (in *VersusSpec) DeepCopy() *VersusSpec {
	if in == nil {
		return nil
	}
	out := new(VersusSpec)
	in.DeepCopyInto(out)
	return out
}
